Add bus interactions to plonkAir to get accepted proof (#2834)
Add execution_bridge, variable_range_checker and bitwise_lookup bus
interactions to PlonkAir.

previously run 
`RUST_LOG=powdr_openvm::powdr_extension::plonk=debug cargo test -r
keccak_plonk_small_prove_mock -- --nocapture`
The result shows: 
`Bus 0 failed to balance the multiplicities ...` which means bus 0
(execution bridge) is not balanced.
Now these unbalanced bus failures are gone apart from two bus types:

pc_lookup: pc bus is still not balanced, I will figure out in another PR
memory lookup: next next reference is not allowed, plonky3 gives error
```
thread 'tests::keccak_plonk_small_prove_mock' panicked at /home/shuang/.cargo/git/checkouts/plonky3-7d8a3b21a665a86f/539bbc8/matrix/src/dense.rs:369:30:
range end index 42 out of range for slice of length 28
```
to handle this case, an extra column needs to be added, I will do it in
another PR.