Improve Plonky3 error when degree bound is exceeded (#2091)
To test, change [this
line](https://github.com/powdr-labs/powdr/blob/3f74b7e0ec36b71a88ff3db6f64af5a6482e9903/std/machines/hash/poseidon_gl.asm#L73)
to:
`array::zip(x7, array::map(a, |a| a * a * a * a * a * a * a), |x7,
expected| x7 = expected);`
and try to prove:
```
$ cargo run pil test_data/std/poseidon_gl_test.asm -o output -f --prove-with plonky3
...
Backend setup for plonky3...
Setup took 0.15889554s
thread 'main' panicked at /Users/georg/coding/powdr/plonky3/src/prover.rs:425:17:
Table main_poseidon has a constraint of degree 7 which exceeds the degree bound of 3.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
whereas on `main`, you'd get:
```
Backend setup for plonky3...
Setup took 0.15057254s
thread 'main' panicked at /Users/georg/.cargo/git/checkouts/plonky3-2a8c63bcd5ef83b0/2192432/fri/src/two_adic_pcs.rs:186:9:
assertion failed: lde.height() >= domain.size()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The message is not great (it should print the constraint that causes
this), but a big improvement. Hopefully, in the future, we'll handle
this automatically by materializing intermediate column.