do not keep temp test files (#2181)
The nightly test passes on the server now in 1h42m, using the same exact
command. However, when run on CI, it fails with the error below.

```console
System.IO.IOException: No space left on device : '/home/runner/runners/2.321.0/_diag/Worker_20241130-025215-utc.log' ...
```

This is potentially caused by the `.release()` function which keeps the
tmp files alive.